#!/usr/bin/env php
<?php


if (file_exists(__DIR__ . '/../autoload.php')) {
    require_once __DIR__ . '/../autoload.php';
} elseif (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
} elseif (file_exists(__DIR__ . '/../../../autoload.php')) {
    require_once __DIR__ . '/../../../autoload.php';
}

//$application = new \GeorgRinger\ExtemconfValidator\Console\Application();

// ... register commands

//$application->run();

$command = new \GeorgRinger\ExtemconfValidator\Console\Application();
$application = new \Symfony\Component\Console\Application();
$application->add($command);
$application->setDefaultCommand($command->getName());
$application->run();
